spring.application.name=E-learning

# Modifier l'URL pour PostgreSQL
spring.datasource.url = jdbc:postgresql://localhost:5432/elearning
spring.datasource.username = postgres
spring.datasource.password = root

# Utiliser le dialecte PostgreSQL pour Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Autres configurations de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration du serveur
server.port=8090


# SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ilgazzkaya599@gmail.com
spring.mail.password=brgq esjz adnv tppb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
