
#----- SonarQube server URL (default to SonarCloud)
sonar.host.url=https://sonarcloud.io

#sonar.scanner.proxyHost=myproxy.mycompany.com
#sonar.scanner.proxyPort=8002
# ==== Informations générales ====
sonar.projectKey=noutailaa_elearning-application-backend
sonar.projectName=ELEARNING APPLICATION BACKEND
sonar.projectVersion=1.0

# ==== Connexion à SonarQube ====
sonar.token=3567e400febf37bee628172faf9c1761e44e2ddc
sonar.login=3567e400febf37bee628172faf9c1761e44e2ddc

# ==== Répertoires sources ====
sonar.sources=src/main/java
#sonar.tests=src/test/java
sonar.java.binaries=target/classes

# ==== Encodage ====
sonar.sourceEncoding=UTF-8

# ==== Langages pris en charge ====
sonar.language=java
sonar.organization=noutailaa